/* One-off generator for cities.json — run it, don't ship it.
 *
 *   node geoint/build-cities.js
 *
 * Why bundle cities at all: naming a country is the model's strong suit, but
 * "somewhere in Iceland" is not a location. Scoring the image against actual
 * place names gets to a town, and GeoNames ships each one WITH coordinates —
 * so the map can plot a guess directly instead of asking a geocoder to turn a
 * region name back into a point. That removes a network round-trip from every
 * scan and, more importantly, removes a dependency that rate-limits.
 *
 * Source: GeoNames cities15000 (every settlement over 15,000 people) plus the
 * admin1 code table, so each city can name its own region. Licensed CC BY 4.0
 * — the attribution rides along in the generated file and is shown in the UI.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const CITIES_URL = "https://download.geonames.org/export/dump/cities15000.zip";
const ADMIN1_URL = "https://download.geonames.org/export/dump/admin1CodesASCII.txt";
const ATTRIBUTION = "Place data from GeoNames (https://www.geonames.org), CC BY 4.0.";

/* A cities15000.zip holds exactly one deflated member, so a full zip reader is
 * overkill — read the local file header and inflate what follows. */
function unzipSingle(buf) {
  if (buf.readUInt32LE(0) !== 0x04034b50) throw new Error("not a zip file");
  const method = buf.readUInt16LE(8);
  const compSize = buf.readUInt32LE(18);
  const nameLen = buf.readUInt16LE(26);
  const extraLen = buf.readUInt16LE(28);
  const start = 30 + nameLen + extraLen;
  const body = compSize > 0 ? buf.subarray(start, start + compSize) : buf.subarray(start);
  if (method === 0) return body;
  if (method !== 8) throw new Error("unexpected compression method " + method);
  return zlib.inflateRawSync(body);
}

async function get(url) {
  const r = await fetch(url, { headers: { "User-Agent": "m3-investigation-tool/1.0 (dataset build)" } });
  if (!r.ok) throw new Error(url + " -> HTTP " + r.status);
  return Buffer.from(await r.arrayBuffer());
}

(async () => {
  process.stdout.write("fetching admin1 code table … ");
  const admin1Raw = (await get(ADMIN1_URL)).toString("utf8");
  const admin1 = new Map();
  for (const line of admin1Raw.split("\n")) {
    const p = line.replace(/\r$/, "").split("\t");
    if (p.length >= 2 && p[0]) admin1.set(p[0], p[1]);   // "IS.01" -> "Höfuðborgarsvæði"
  }
  console.log(admin1.size + " regions");

  process.stdout.write("fetching cities15000 … ");
  const rows = unzipSingle(await get(CITIES_URL)).toString("utf8").trim().split("\n");
  console.log(rows.length + " cities");

  // region names are shared by many cities, so they live in one table
  const regionNames = [];
  const regionIndex = new Map();
  const regionId = (name) => {
    if (!name) return -1;
    if (!regionIndex.has(name)) { regionIndex.set(name, regionNames.length); regionNames.push(name); }
    return regionIndex.get(name);
  };

  const byCountry = {};
  let skipped = 0;
  for (const line of rows) {
    const f = line.replace(/\r$/, "").split("\t");
    const name = f[1], lat = Number(f[4]), lon = Number(f[5]);
    const cc = f[8], a1 = f[10], pop = parseInt(f[14], 10) || 0;
    if (!name || !cc || !isFinite(lat) || !isFinite(lon)) { skipped++; continue; }
    const region = admin1.get(cc + "." + a1) || null;
    // 4dp is ~11m, far finer than a town centroid needs, and it halves the file
    (byCountry[cc] || (byCountry[cc] = [])).push([
      name, regionId(region), Number(lat.toFixed(4)), Number(lon.toFixed(4)), pop,
    ]);
  }
  // biggest first, so capping a long list keeps the places a photo is likely from
  for (const cc of Object.keys(byCountry)) byCountry[cc].sort((a, b) => b[4] - a[4]);

  const out = {
    note: "Generated by geoint/build-cities.js. Do not edit by hand.",
    attribution: ATTRIBUTION,
    fields: ["name", "regionIndex", "lat", "lon", "population"],
    regions: regionNames,
    byCountry,
  };
  const file = path.join(__dirname, "cities.json");
  fs.writeFileSync(file, JSON.stringify(out));

  const total = Object.values(byCountry).reduce((n, a) => n + a.length, 0);
  const biggest = Object.entries(byCountry).sort((a, b) => b[1].length - a[1].length).slice(0, 5);
  console.log(`cities.json: ${total} cities across ${Object.keys(byCountry).length} countries, ` +
    `${regionNames.length} region names, ${(fs.statSync(file).size / 1048576).toFixed(2)} MB` +
    (skipped ? ` (${skipped} rows skipped)` : ""));
  console.log("  largest:", biggest.map(([cc, a]) => cc + "=" + a.length).join(" "));
})().catch((e) => { console.error("FAILED:", e.message); process.exit(1); });
