"use strict";
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  connect: (cfg) => ipcRenderer.invoke("db:connect", cfg),
  disconnect: () => ipcRenderer.invoke("db:disconnect"),
  search: (term) => ipcRenderer.invoke("db:search", term),
  pickSqlite: () => ipcRenderer.invoke("db:pickSqlite"),
  listTables: () => ipcRenderer.invoke("db:listTables"),
  searchTable: (table, term) => ipcRenderer.invoke("db:searchTable", { table, term }),
  pickSqlFile: () => ipcRenderer.invoke("db:pickSqlFile"),
  importSqlFile: (filePath) => ipcRenderer.invoke("db:importSqlFile", filePath),
  onImportProgress: (cb) => ipcRenderer.on("db:importProgress", (_e, data) => cb(data)),
  checkHandle: (handle) => ipcRenderer.invoke("osint:check", handle),
  onOsintResult: (cb) => ipcRenderer.on("osint:result", (_e, data) => cb(data)),
  osintLookup: (query, type) => ipcRenderer.invoke("osint:lookup", { query, type }),
  appVersion: () => ipcRenderer.invoke("app:version"),
  authMe: () => ipcRenderer.invoke("auth:me"),
  authRegister: (username, password) => ipcRenderer.invoke("auth:register", { username, password }),
  authLogin: (username, password) => ipcRenderer.invoke("auth:login", { username, password }),
  authLogout: () => ipcRenderer.invoke("auth:logout"),
  searchStart: (ultra, type, query) => ipcRenderer.invoke("search:start", { ultra, type, query }),
  meUpdate: (patch) => ipcRenderer.invoke("me:update", patch),
  discordConnect: (discord_id) => ipcRenderer.invoke("discord:connect", discord_id),
  discordDisconnect: () => ipcRenderer.invoke("discord:disconnect"),
  openExternal: (url) => ipcRenderer.invoke("open:external", url),
  bookmarksList: () => ipcRenderer.invoke("bookmarks:list"),
  bookmarksAdd: (bm) => ipcRenderer.invoke("bookmarks:add", bm),
  bookmarksDelete: (id) => ipcRenderer.invoke("bookmarks:delete", id),
  stats: () => ipcRenderer.invoke("stats:get"),
  annList: () => ipcRenderer.invoke("ann:list"),
  annPost: (title, body) => ipcRenderer.invoke("ann:post", { title, body }),
  annDelete: (id) => ipcRenderer.invoke("ann:delete", id),
  adminUsers: () => ipcRenderer.invoke("admin:users"),
  adminPatchUser: (id, patch) => ipcRenderer.invoke("admin:patchUser", { id, patch }),
  adminGrantTokens: (id, delta) => ipcRenderer.invoke("admin:grantTokens", { id, delta }),
  adminRenameUser: (id, username) => ipcRenderer.invoke("admin:renameUser", { id, username }),
  adminDeleteUser: (id) => ipcRenderer.invoke("admin:deleteUser", id),
  adminLogs: (limit) => ipcRenderer.invoke("admin:logs", limit),
  codesRedeem: (code) => ipcRenderer.invoke("codes:redeem", code),
  geointAnalyze: (payload) => ipcRenderer.invoke("geoint:analyze", payload),
  geointStreetview: (lat, lon) => ipcRenderer.invoke("geoint:streetview", { lat, lon }),
  geointRegions: () => ipcRenderer.invoke("geoint:regions"),
  geointPick: (payload) => ipcRenderer.invoke("geoint:pick", payload),
  adminCodesList: () => ipcRenderer.invoke("admin:codesList"),
  adminCodeCreate: (payload) => ipcRenderer.invoke("admin:codeCreate", payload),
  adminCodeDelete: (id) => ipcRenderer.invoke("admin:codeDelete", id),
  checkUpdate: () => ipcRenderer.invoke("update:check"),
  installUpdate: (url) => ipcRenderer.invoke("update:install", url),
  onUpdateProgress: (cb) => ipcRenderer.on("update:progress", (_e, data) => cb(data)),
});
